name: Demo Build & Publish Artifacts
on: 
  push: 
    branches: [ "master" ]
    paths: 'demo'
  workflow_dispatch: 
jobs:
  build_n_publish:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
