name: Demo Build & Publish Artifacts
on: 
  push: 
    branches: [ "github_actions" ]
    paths: 'demo'
  workflow_dispatch: 
jobs:
  build_n_publish:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        
      - name: 'Extract Artifact Version To Use'
        run: |
          gsutil cp gs://ky_github_actions/demo_version version
          version=$(<version)
          if grep -q "SNAPSHOT" <<< "$version";
          then
             echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV   
          else 
            MAJOR=$(echo $version | cut -f1 -d.)
            MINOR=$(echo $version | cut -f2 -d.)
            PATCH=$(echo $version | cut -f3 -d.)
            PATCH=$((PATCH+1))
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
            echo "NEW_VERSION=$version" >> $GITHUB_ENV 
          fi
      
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.8.0'
      
      - name: 'Build & Publish Java Artifact'
        run: |
          echo ${{ env.NEW_VERSION }}
          
          
          
          
          
          
          
          
          
          
          
          
